name: Continuos Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_project:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pip and packages
        uses: luisgs7/pip-packages@v1

      - name: Run Tests
        env:
          ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
        run: python manage.py test